name: "Linting ES code ..."

jobs:
  Linting:
    runs-on: ubuntu-latest
    if: true
    steps:
      - uses: actions/checkout@v2
      - run: set -xeuo pipefail
      - name: Linting => ${{ github.ref }}
        run: |
          echo "linting the Code ..."
          npm ci
          npm run lint
          echo "lint completed!"
